all:
	cc -o prog_1 prog_1.c input_int.c input_long.c parcel.c -lreadline file_readline.c sort.c -g -Wall -Wextra
	cc -o prog_2 prog_2.c input_int.c input_long.c parcel.c -lreadline file_readline.c sort.c generate.c -g -Wall -Wextra
